package io.github.ygaray.yahirandroidtaste.theme

import androidx.compose.ui.graphics.Color

// Primary — Teal (anchored to seed #2FC3B2, MTB-derived)
val TealPrimary                   = Color(0xFF006875)
val TealOnPrimary                 = Color(0xFFFFFFFF)
val TealPrimaryContainer          = Color(0xFF9EEEFF)
val TealOnPrimaryContainer        = Color(0xFF001F24)
val TealPrimaryDark               = Color(0xFF53D7E9)
val TealOnPrimaryDark             = Color(0xFF003640)
val TealPrimaryContainerDark      = Color(0xFF004E5B)
val TealOnPrimaryContainerDark    = Color(0xFF9EEEFF)

// Secondary — Slate (MTB-derived muted teal-grey; intentional understated accent)
val SlateSecondary                = Color(0xFF4A6267)
val SlateOnSecondary              = Color(0xFFFFFFFF)
val SlateSecondaryContainer       = Color(0xFFCCE8EE)
val SlateOnSecondaryContainer     = Color(0xFF041F24)
val SlateSecondaryDark            = Color(0xFFB1CBD1)
val SlateOnSecondaryDark          = Color(0xFF1D3439)
val SlateSecondaryContainerDark   = Color(0xFF334B50)
val SlateOnSecondaryContainerDark = Color(0xFFCCE8EE)

// Tertiary — Amber [HAND-TUNED: warm gold for favorite/star icon tint]
val AmberTertiary                 = Color(0xFF7B5A00)
val AmberOnTertiary               = Color(0xFFFFFFFF)
val AmberTertiaryContainer        = Color(0xFFFFE0A0)
val AmberOnTertiaryContainer      = Color(0xFF251A00)
val AmberTertiaryDark             = Color(0xFFF9BE6A)
val AmberOnTertiaryDark           = Color(0xFF3E2C00)
val AmberTertiaryContainerDark    = Color(0xFF563D00)
val AmberOnTertiaryContainerDark  = Color(0xFFFFE0A0)

// Error — Red (M3 standard)
val ErrorRed                      = Color(0xFFBA1A1A)
val OnErrorRed                    = Color(0xFFFFFFFF)
val ErrorRedContainer             = Color(0xFFFFDAD6)
val OnErrorRedContainer           = Color(0xFF410002)
val ErrorRedDark                  = Color(0xFFFFB4AB)
val OnErrorRedDark                = Color(0xFF690005)
val ErrorRedContainerDark         = Color(0xFF93000A)
val OnErrorRedContainerDark       = Color(0xFFFFDAD6)

// Neutral Surfaces — Light (MTB-derived)
val NeutralBgLight                = Color(0xFFF5FAFB)
val NeutralOnBgLight              = Color(0xFF171D1E)
val NeutralSurfaceVarLight        = Color(0xFFDAE4E7)
val NeutralOnSurfaceVarLight      = Color(0xFF3F4D50)
val OutlineLight                  = Color(0xFF6F797C)
val OutlineVarLight               = Color(0xFFBEC8CB)
val ScrimColor                    = Color(0xFF000000)
val InverseSurfaceLight           = Color(0xFF2B3235)
val InverseOnSurfaceLight         = Color(0xFFEDF3F5)
val InversePrimaryLight           = Color(0xFF53D7E9)

// Elevation Ramp — Light (MTB-derived neutral tones)
val SurfaceDimLight               = Color(0xFFD5DBE0)
val SurfaceBrightLight            = Color(0xFFF5FAFB)
val SurfaceContainerLowestLight   = Color(0xFFFFFFFF)
val SurfaceContainerLowLight      = Color(0xFFEEF4F6)
val SurfaceContainerLight         = Color(0xFFE8EFF0)
val SurfaceContainerHighLight     = Color(0xFFE2E9EB)
val SurfaceContainerHighestLight  = Color(0xFFDCE3E5)

// Neutral Surfaces — Dark [D-02: ink base #0B1F1E, LOCKED]
val InkBackground                 = Color(0xFF0B1F1E)
val InkSurface                    = Color(0xFF0B1F1E)
val InkOnBackground               = Color(0xFFDEE4E5)
val InkOnSurface                  = Color(0xFFDEE4E5)
val NeutralSurfaceVarDark         = Color(0xFF3F4D50)
val NeutralOnSurfaceVarDark       = Color(0xFFBEC8CB)
val OutlineDark                   = Color(0xFF899295)
val OutlineVarDark                = Color(0xFF3F4D50)
val InverseSurfaceDark            = Color(0xFFDEE4E5)
val InverseOnSurfaceDark          = Color(0xFF2B3235)
val InversePrimaryDark            = Color(0xFF006875)

// Elevation Ramp — Dark [D-02: tuned over ink #0B1F1E]
val SurfaceDimDark                = Color(0xFF060F0E)
val SurfaceBrightDark             = Color(0xFF364F4D)
val SurfaceContainerLowestDark    = Color(0xFF071110)
val SurfaceContainerLowDark       = Color(0xFF0F2120)
val SurfaceContainerDark          = Color(0xFF152927)
val SurfaceContainerHighDark      = Color(0xFF1B302E)
val SurfaceContainerHighestDark   = Color(0xFF213836)
